# Generated by Django 4.0.6 on 2022-07-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Characters_rick_morty')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('izmerenie', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='location_rick_morty')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('numb_episode', models.IntegerField()),
                ('desc', models.TextField(max_length=255)),
                ('img', models.ImageField(upload_to='episode_rick_morty')),
                ('characters', models.ManyToManyField(blank=True, null=True, to='mainapp.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='birth_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_birth', to='mainapp.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.location'),
        ),
    ]
