# Generated by Django 4.0.6 on 2022-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_character_gender_alter_character_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('ml', 'male'), ('fm', 'female'), ('gl', 'genderless'), ('un', 'unknown')], max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('al', 'alive'), ('dd', 'dead'), ('un', 'unknown')], max_length=255),
        ),
    ]
