# Generated by Django 4.0.6 on 2022-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_character_gender_alter_character_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='episode_rick_morty'),
        ),
    ]
